const ItemModType = {
  MANA: 0,
  HEALTH: 1,
  AGILITY: 3,
  STRENGTH: 4,
  INTELLECT: 5,
  SPIRIT: 6,
  STAMINA: 7,
  DEFENSE_SKILL_RATING: 12,
  DODGE_RATING: 13,
  PARRY_RATING: 14,
  BLOCK_RATING: 15,
  HIT_MELEE_RATING: 16,
  HIT_RANGED_RATING: 17,
  HIT_SPELL_RATING: 18,
  CRIT_MELEE_RATING: 19,
  CRIT_RANGED_RATING: 20,
  CRIT_SPELL_RATING: 21,
  HIT_TAKEN_MELEE_RATING: 22,
  HIT_TAKEN_RANGED_RATING: 23,
  HIT_TAKEN_SPELL_RATING: 24,
  CRIT_TAKEN_MELEE_RATING: 25,
  CRIT_TAKEN_RANGED_RATING: 26,
  CRIT_TAKEN_SPELL_RATING: 27,
  HASTE_MELEE_RATING: 28,
  HASTE_RANGED_RATING: 29,
  HASTE_SPELL_RATING: 30,
  HIT_RATING: 31,
  CRIT_RATING: 32,
  HIT_TAKEN_RATING: 33,
  CRIT_TAKEN_RATING: 34,
  RESILIENCE_RATING: 35,
  HASTE_RATING: 36,
  EXPERTISE_RATING: 37,
  ATTACK_POWER: 38,
  RANGED_ATTACK_POWER: 39,
  SPELL_HEALING_DONE: 41, // deprecated
  SPELL_DAMAGE_DONE: 42, // deprecated
  MANA_REGENERATION: 43,
  ARMOR_PENETRATION_RATING: 44,
  SPELL_POWER: 45,
  HEALTH_REGEN: 46,
  SPELL_PENETRATION: 47,
  BLOCK_VALUE: 48
};

const ItemModTypeMap = new Map([
  [ItemModType.MANA, "Mana"],
  [ItemModType.HEALTH, "Health"],
  [ItemModType.AGILITY, "Agility"],
  [ItemModType.STRENGTH, "Strength"],
  [ItemModType.INTELLECT, "Intellect"],
  [ItemModType.SPIRIT, "Spirit"],
  [ItemModType.STAMINA, "Stamina"],
  [ItemModType.DEFENSE_SKILL_RATING, "defense rating"],
  [ItemModType.DODGE_RATING, "dodge rating"],
  [ItemModType.PARRY_RATING, "parry rating"],
  [ItemModType.BLOCK_RATING, "block rating"],
  [ItemModType.HIT_MELEE_RATING, "melee hit rating"],
  [ItemModType.HIT_RANGED_RATING, "ranged hit rating"],
  [ItemModType.HIT_SPELL_RATING, "spell hit rating"],
  [ItemModType.CRIT_MELEE_RATING, "melee crit rating"],
  [ItemModType.CRIT_RANGED_RATING, "ranged crit rating"],
  [ItemModType.CRIT_SPELL_RATING, "spell crit rating"],
  [ItemModType.HIT_TAKEN_MELEE_RATING, "melee hit taken rating"],
  [ItemModType.HIT_TAKEN_RANGED_RATING, "ranged hit taken rating"],
  [ItemModType.HIT_TAKEN_SPELL_RATING, "spell hit taken rating"],
  [ItemModType.CRIT_TAKEN_MELEE_RATING, "melee crit taken rating"],
  [ItemModType.CRIT_TAKEN_RANGED_RATING, "ranged crit taken rating"],
  [ItemModType.CRIT_TAKEN_SPELL_RATING, "spell crit taken rating"],
  [ItemModType.HASTE_MELEE_RATING, "melee haste rating"],
  [ItemModType.HASTE_RANGED_RATING, "ranged haste rating"],
  [ItemModType.HASTE_SPELL_RATING, "spell haste rating"],
  [ItemModType.HIT_RATING, "hit rating"],
  [ItemModType.CRIT_RATING, "critical strike rating"],
  [ItemModType.HIT_TAKEN_RATING, "hit taken rating"],
  [ItemModType.CRIT_TAKEN_RATING, "crit taken rating"],
  [ItemModType.RESILIENCE_RATING, "resilience rating"],
  [ItemModType.HASTE_RATING, "haste rating"],
  [ItemModType.EXPERTISE_RATING, "expertise rating"],
  [ItemModType.ATTACK_POWER, "attack power"],
  [ItemModType.RANGED_ATTACK_POWER, "ranged attack power rating"],
  [ItemModType.SPELL_HEALING_DONE, "spell healing rating"], // deprecated
  [ItemModType.SPELL_DAMAGE_DONE, "spell damage rating"], // deprecated
  [ItemModType.MANA_REGENERATION, "mana per 5 sec"],
  [ItemModType.ARMOR_PENETRATION_RATING, "armor penetration rating"],
  [ItemModType.SPELL_POWER, "spellpower"],
  [ItemModType.HEALTH_REGEN, "health per 5 sec"],
  [ItemModType.SPELL_PENETRATION, "spell penetration rating"],
  [ItemModType.BLOCK_VALUE, "block value"]
]);

export default {
  name: "ItemStatTypes",

  GetStatType: function(stat) {
    return ItemModTypeMap.get(stat);
  }
};
