export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS'

export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'

export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ALL_MANUFACTURERS = 'ALL_MANUFACTURER'
export const ALL_MANUFACTURERS_SUCCESS = 'ALL_MANUFACTURER_SUCCESS'

export const UPDATE_USER = 'UPDATE_USER'

export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR   = 'AUTH_ERROR'
export const AUTH_LOGOUT  = 'AUTH_LOGOUT'

export const VOTE_REQUEST_BEGIN   = 'VOTE_REQUEST_BEGIN'
export const VOTE_REQUEST_SUCCESS = 'VOTE_REQUEST_SUCCESS'
export const VOTE_REQUEST_ERROR   = 'VOTE_REQUEST_ERROR'

export const VOTE_TIMERS_REQUEST  = 'VOTE_TIMERS_REQUEST'
export const VOTE_TIMERS_SUCCESS  = 'VOTE_TIMERS_SUCCESS'
export const VOTE_TIMERS_ERROR    = 'VOTE_TIMERS_ERROR'

export const VOTE_BEGIN   = 'VOTE_BEGIN'
export const VOTE_SUCCESS = 'VOTE_SUCCESS'
export const VOTE_ERROR   = 'VOTE_ERROR'

export const NEWS_REQUEST = 'NEWS_REQUEST'
export const NEWS_SUCCESS = 'NEWS_SUCCESS'
export const NEWS_ERROR   = 'NEWS_ERROR'