export const UPDATE_PAGE_TITLE = "UPDATE_PAGE_TITLE";

export const UPDATE_USER = "UPDATE_USER";

export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const VOTE_REQUEST_BEGIN = "VOTE_REQUEST_BEGIN";
export const VOTE_REQUEST_SUCCESS = "VOTE_REQUEST_SUCCESS";
export const VOTE_REQUEST_ERROR = "VOTE_REQUEST_ERROR";

export const VOTE_TIMERS_REQUEST = "VOTE_TIMERS_REQUEST";
export const VOTE_TIMERS_SUCCESS = "VOTE_TIMERS_SUCCESS";
export const VOTE_TIMERS_ERROR = "VOTE_TIMERS_ERROR";

export const VOTE_BEGIN = "VOTE_BEGIN";
export const VOTE_SUCCESS = "VOTE_SUCCESS";
export const VOTE_ERROR = "VOTE_ERROR";

export const NEWS_REQUEST = "NEWS_REQUEST";
export const NEWS_SUCCESS = "NEWS_SUCCESS";
export const NEWS_ERROR = "NEWS_ERROR";
export const NEWS_UPDATE = "NEWS_UPDATE";
export const NEWS_INSERT = "NEWS_INSERT";
export const NEWS_DELETE = "NEWS_DELETE";
export const NEWS_COMMENTS_INSERT = "NEWS_COMMENTS_INSERT";
export const NEWS_COMMENTS_REQUEST = "NEWS_COMMENTS_REQUEST";
export const NEWS_COMMENTS_SUCCESS = "NEWS_COMMENTS_SUCCESS";
export const NEWS_COMMENTS_ERROR = "NEWS_COMMENTS_ERROR";
